image: node:6.11.2-alpine
before_script:
  - apk update && apk add openssl ca-certificates
  - npm install
  - PATH=$(npm bin):$PATH
pages:
  script:
  - npm run build
  artifacts:
    paths:
    - public
  only:
  - master