baseURL = "https://yuniql.io"
languageCode = "en-us"
title = "YUNIQL"
theme = "kube-yuniql"
description = "YUNIQL (yuu-nee-kel) is a database versioning and migration engine for SqlServer, PostgreSql and others. Use plain SQL to promote and facilitate end-to-end DB DevOps discipline. Provision fresh database every test run and manage releases via continuous delivery pipeline tasks."
Paginate = 4

[Params]
  RSSLink = "/index.xml"
  author = "YUNIQL" # add your company name
  github = "rdagumampan" # add your github profile name
  twitter = "rdagumampan" # add your twitter profile
  email = "rdagumampan@gmail.com"

[[menu.main]]
    name = "Get started"
    weight = 1
    url = "https://github.com/rdagumampan/yuniql/wiki/Getting-started"

[[menu.main]]
    name = "How it Works"
    weight = 2
    url = "https://github.com/rdagumampan/yuniql/wiki/How-yuniql-works"

[[menu.main]]
    name = "Report bug"
    weight = 3
    url = "https://github.com/rdagumampan/yuniql/issues/new"
