baseURL = "https://rdagumampan.github.io/yuniql.io"
languageCode = "en-us"
title = "YUNIQL"
theme = "kube-yuniql"
description = "YUNIQL (yuu-nee-kel) is an open source schema versioning and database migration engine for SqlServer, PostgreSql and others. Improve your Data Platform DevOps discipline with repeatable deployment, plain SQL scripts, bulk import, integrated CI/CD pipelines, and Docker-based migrations."
Paginate = 4

[Params]
  RSSLink = "/index.xml"
  author = "Rodel E. Dagumampan" # add your company name
  github = "rdagumampan" # add your github profile name
  twitter = "rdagumampan" # add your twitter profile
  email = "rdagumampan@gmail.com"

[[menu.main]]
    name = "Get started"
    weight = 1
    url = "/docs/get-started/"

[[menu.main]]
    name = "How it works"
    weight = 2
    url = "/docs/how-yuniql-works/"

[[menu.main]]
    name = "Report issue"
    weight = 3
    url = "https://github.com/rdagumampan/yuniql/issues/new"
